feat: Add seperate eslint config for Vue2 code
silvermine/eslint-config-silvermine pull request #75
Opened 2021-11-30 22:16 UTC by crgwbr

2021-11-30 22:17 UTC, jthomerson commented
Nit: spelling of "separate" in commit / PR title

2021-11-30 22:22 UTC, crgwbr commented
> Nit: spelling of "separate" in commit / PR title

Fixed. Someday I'll learn how to spell…

2021-12-01 16:45 UTC, yokuze requested changes

2021-12-01 16:45 UTC, yokuze commented on partials/vue.js
> +const silvermineRules = {
It looks like this object still contains Vue-3-specific rules, which means they are getting mixed into the Vue 2 config. For example, `vue/no-deprecated-v-is` applies to Vue 3 only.

We probably need separate object structures for base rules, Vue 2 rules, and Vue 3 rules.

2021-12-14 14:57 UTC, crgwbr commented
Ready for your re-review @yokuze

2021-12-14 16:40 UTC, yokuze approved these changes
This LGTM. Thanks @crgwbr !

2021-12-14 16:41 UTC, yokuze commented
@jthomerson please merge at will. @crgwbr can correct me if I'm wrong, but I don't think we will need a new NPM version until it's all tested and we are ready to tag a final version.

2021-12-14 22:04 UTC, merged